name: dockerhub

on:
  push:
    branches: [ main, devel ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push master
        uses: docker/build-push-action@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/docker-restarter:latest
          platforms: linux/amd64,linux/arm64
      -
        name: Build and push devel
        uses: docker/build-push-action@v4
        if: ${{ github.ref_name == 'devel' }}
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/docker-restarter:dev
          platforms: linux/amd64,linux/arm64
